#include "support/thumbgrid_test_support.h"

#include <QDir>
#include <QSignalSpy>
#include <QTemporaryDir>

#include "components/thumbnailer/thumbnailer.h"

// The in-memory thumbnail cache: a repeated request for an unchanged file or
// folder is answered synchronously (no worker round-trip), a changed file is
// re-generated, the cache honors its configurable size limit, and 0 disables it.
class ThumbnailMemCacheTest : public QObject {
    Q_OBJECT

private slots:
    void repeatedFileRequestIsServedSynchronously();
    void repeatedDirRequestIsServedSynchronously();
    void modifiedFileIsRegenerated();
    void limitZeroDisablesTheMemoryCache();
    void leastRecentlyUsedEntriesAreEvicted();
};

namespace {
    const int thumbSize = 200;

    // Backdates a file so a later rewrite is guaranteed to change its mtime
    // without sleeping through mtime resolution.
    bool backdate(const QString &path) {
        QFile f(path);
        if(!f.open(QIODevice::Append))
            return false;
        return f.setFileTime(QDateTime::currentDateTime().addSecs(-10), QFileDevice::FileModificationTime);
    }
}

void ThumbnailMemCacheTest::repeatedFileRequestIsServedSynchronously() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString img = dir.filePath("a.png");
    QVERIFY(tgtest::writeImage(img, Qt::red));

    Thumbnailer thumbnailer;
    QSignalSpy ready(&thumbnailer, &Thumbnailer::thumbnailReady);

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    QTRY_COMPARE(ready.count(), 1);

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    // no event loop between request and check: only a memory hit can answer
    QCOMPARE(ready.count(), 2);
}

void ThumbnailMemCacheTest::repeatedDirRequestIsServedSynchronously() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    QVERIFY(QDir(dir.path()).mkpath("sub"));
    QVERIFY(tgtest::writeImage(dir.filePath("sub/a.png"), Qt::green));

    Thumbnailer thumbnailer;
    QSignalSpy ready(&thumbnailer, &Thumbnailer::dirThumbnailReady);

    thumbnailer.getDirThumbnailAsync(dir.filePath("sub"), thumbSize, false, false, false);
    QTRY_COMPARE(ready.count(), 1);

    thumbnailer.getDirThumbnailAsync(dir.filePath("sub"), thumbSize, false, false, false);
    QCOMPARE(ready.count(), 2);
}

void ThumbnailMemCacheTest::modifiedFileIsRegenerated() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString img = dir.filePath("a.png");
    QVERIFY(tgtest::writeImage(img, Qt::red));
    QVERIFY(backdate(img));

    Thumbnailer thumbnailer;
    QSignalSpy ready(&thumbnailer, &Thumbnailer::thumbnailReady);

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    QTRY_COMPARE(ready.count(), 1);

    // rewrite with current mtime: the cached entry must be treated as stale
    QVERIFY(tgtest::writeImage(img, Qt::blue));

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    QCOMPARE(ready.count(), 1); // not a synchronous memory hit
    QTRY_COMPARE(ready.count(), 2); // regenerated by a worker
}

void ThumbnailMemCacheTest::limitZeroDisablesTheMemoryCache() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString img = dir.filePath("a.png");
    QVERIFY(tgtest::writeImage(img, Qt::red));

    Thumbnailer thumbnailer;
    settings->setThumbnailerMemCacheLimit(0);
    settings->sendChangeNotification(); // applies the new limit to the live instance
    QSignalSpy ready(&thumbnailer, &Thumbnailer::thumbnailReady);

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    QTRY_COMPARE(ready.count(), 1);

    thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
    QCOMPARE(ready.count(), 1); // nothing cached, so nothing synchronous
    QTRY_COMPARE(ready.count(), 2);

    settings->setThumbnailerMemCacheLimit(64);
}

void ThumbnailMemCacheTest::leastRecentlyUsedEntriesAreEvicted() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());

    // ~117 KB per 200x150 thumbnail; a 1 MB budget holds at most ~8
    const int imageCount = 12;
    QStringList images;
    for(int i = 0; i < imageCount; i++) {
        QString img = dir.filePath(QString("img%1.png").arg(i));
        QVERIFY(tgtest::writeImage(img, Qt::yellow));
        images << img;
    }

    Thumbnailer thumbnailer;
    settings->setThumbnailerMemCacheLimit(1);
    settings->sendChangeNotification();
    QSignalSpy ready(&thumbnailer, &Thumbnailer::thumbnailReady);

    for(const QString &img : images) {
        thumbnailer.getThumbnailAsync(img, thumbSize, false, false);
        QTRY_VERIFY(ready.count() > images.indexOf(img));
    }
    QTRY_COMPARE(ready.count(), imageCount);

    // the newest entry survived, the oldest was evicted
    thumbnailer.getThumbnailAsync(images.last(), thumbSize, false, false);
    QCOMPARE(ready.count(), imageCount + 1);

    thumbnailer.getThumbnailAsync(images.first(), thumbSize, false, false);
    QCOMPARE(ready.count(), imageCount + 1); // miss: goes back to a worker
    QTRY_COMPARE(ready.count(), imageCount + 2);

    settings->setThumbnailerMemCacheLimit(64);
}

TG_BEHAVIOR_TEST_MAIN(ThumbnailMemCacheTest)

#include "test_thumbnail_mem_cache.moc"
